### ISSUE TITLE
Contributing as maintainer to the project

### ISSUE THREAD

**Issue by mhadaily** [iampawan/GDG-DevFest-App#1]
Hi, 

First thanks for the fantastic work. 

I have been working on a similar project with Flutter to make it ready for (hoverboard) same as you did. Today, I have found that you have actually finished it before me 😄 which is great. 
Just wondering if you'd like to have someone else to help you maintain this project along with you and possibly we may ask github.com/gdg-x or Abraham Williams who is now the maintainer of hoverboard to move this project under the GDG-X organization. 

I will understand if you have different opinions and will respect them. 

Please keep doing great work dude.
Majid

**Comment by iampawan** [comment]
Hey, @mhadaily thanks for reaching out. Yes, I would be more than happy to have other maintainers for this project. I would be happy if we can leave the repo here only but in case if moving this project can help more people or can add benefits then we can think about it too.

Thanks

**Comment by mhadaily** [comment]
sounds great, happy to be on board.
