### ISSUE TITLE
About FCM

### ISSUE THREAD

**Issue by PatilShreyas** [iampawan/GDG-DevFest-App#5]
How it is if Firebase Cloud Messaging is implemented in this app so that DevFest organisers can send notifications to all users to keep them engaged and to know about latest updates/changes/alerts.

For.e.g.
1) Two Days to go For DevFest!!! 
2) Our Speaker ABC will talk about XYZ.
3) The venue is ABCXYZ.

**Comment by iampawan** [comment]
It's already in my list and the good news is that it is already integrated into the firebase branch which is not yet published. We are working on the admin panel and then we will push them here.

**Comment by PatilShreyas** [comment]
Oh. Nice!
