### ISSUE TITLE
Local notifications

### ISSUE THREAD

**Issue by TJMusiitwa** [iampawan/GDG-DevFest-App#7]
Hey Pawan I was posting a feature request. Given that this is an events app, it would be cool if you could add **local notifications**  for the sessions that would be able to notify the user of a session about to commence.
I have done some work on this on a separate project that I am working on but it would be good given your expertise to show  methods of doing this  in addition to state management.

Thanks

**Comment by abc873693** [comment]
May be use [flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications) implement?
I will add this feature in my fork repository.
Have any need to notice?
