### ISSUE TITLE
agenda detail screen: There are multiple heroes that share the same tag within a subtree

### ISSUE THREAD

**Issue by buildbro** [iampawan/GDG-DevFest-App#9]
I get the following error: "There are multiple heroes that share the same tag within a subtree" on agenda_detail.dart.
The app screen goes black when a session list item is tapped.
My investigation shows that this is caused when 2 session items have the same URL for speakerImage.

**Comment by Physicx101** [comment]
Yes that is correct, you cannot have same values for hero tag, so you're gonna have to find a value which is unique either an id or just try to differentiate the image URL
